# Generated by Django 5.0.1 on 2026-02-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntryBackups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('particular_credit', models.CharField(blank=True, max_length=200, null=True)),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('particular_debit', models.CharField(blank=True, max_length=200, null=True)),
                ('debit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('flag', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
